version: 2.1

orbs:
  codecov: codecov/codecov@3.2.4

jobs:
  build_and_test:
    docker:
      - image: cimg/openjdk:19.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - codecov/upload:

workflows:
  build_and_test:
    jobs:
      - build_and_test:
        filters:
          branches:
            only: master
